# NLP

In [65]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [66]:
df = pd.read_csv("train.txt", sep = ";",header=None, names=["title","emotions"])

In [67]:
df.head()

                                               title emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [68]:
df.isnull().sum()

title       0
emotions    0
dtype: int64

In [69]:
df["emotions"].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [70]:
unique_emotions = df["emotions"].unique() 
emotion_num = {}
i = 0

for emo in unique_emotions: 
    emotion_num[emo] = i
    i +=1
    print(emotion_num)

df["emotions"] = df["emotions"].map(emotion_num)

{'sadness': 0}
{'sadness': 0, 'anger': 1}
{'sadness': 0, 'anger': 1, 'love': 2}
{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3}
{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4}
{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

## Text Preprocessing/Cleaning  for ML

### Step1: Lower Case

In [71]:
# To make short function lambda is used 

df["title"] = df["title"].apply(lambda x : x.lower())

In [72]:
df.head()

                                               title  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

## Step2: Remove Punctuation

In [73]:
import string 

def remove_punchu(txt): 
    return txt.translate(str.maketrans("","",string.punctuation))

In [74]:
df["title"] = df['title'].apply(remove_punchu)

In [75]:
df.head()

                                               title  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

## Step3: Removing Numbers

In [76]:
def remove_nums(txt): 
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new 

df['title'] = df['title'].apply(remove_nums)

In [77]:
df.head()

                                               title  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

## Removing Emojis and Special Characters

In [78]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new +=i
    return new 

df['title'] = df['title'].apply(remove_emojis)

In [79]:
df.head()

                                               title  emotions
0                            i didnt feel humiliated         0
1  i can go from feeling so hopeless to so damned...         0
2   im grabbing a minute to post i feel greedy wrong         1
3  i am ever feeling nostalgic about the fireplac...         2
4                               i am feeling grouchy         1

## Remove Stopwords

- Note: Doing all the other tasks are easy but for removing the stop words like 'is','the','are' etc we have to use a library and that is NLTK(Natural Language Toolkit).

In [80]:
import nltk

In [81]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [82]:
nltk.download("punkt")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [83]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [84]:
len(stop_words)

198

In [85]:
df

                                                   title  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [86]:
def remove(txt): 
    words = txt.split()
    cleaned = []
    for i in words:
        if not i in stop_words: 
            cleaned.append(i)
    return " ".join(cleaned)

In [87]:
df['title'] = df['title'].apply(remove)

In [88]:
df.head()

                                               title  emotions
0                              didnt feel humiliated         0
1  go feeling hopeless damned hopeful around some...         0
2          im grabbing minute post feel greedy wrong         1
3  ever feeling nostalgic fireplace know still pr...         2
4                                    feeling grouchy         1

## Feature Extraction/Vectorization

## Bag Of Words

In [89]:
from sklearn.feature_extraction.text import CountVectorizer 

documents = [
    "I love pizza", 
    "Pizza is the best", 
    "I love pasta", 
    "Pasta is great"
]

vectorizer = CountVectorizer() 

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out()) 
print("\n BoW Matrix: \n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

 BoW Matrix:
 [[0 0 0 1 0 1 0]
 [1 0 1 0 0 1 1]
 [0 0 0 1 1 0 0]
 [0 1 1 0 1 0 0]]

## Bigram and Trigram

In [90]:
from sklearn.feature_extraction.text import CountVectorizer 

documents = [
    "I love pizza", 
    "Pizza is the best", 
    "I love pasta", 
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range=(2,2)) 

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out()) 
print("\n BoW Matrix: \n", X.toarray())

Vocabulary: ['is great' 'is the' 'love pasta' 'love pizza' 'pasta is' 'pizza is'
 'the best']

 BoW Matrix:
 [[0 0 0 1 0 0 0]
 [0 1 0 0 0 1 1]
 [0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0]]

In [91]:
from sklearn.feature_extraction.text import CountVectorizer 

documents = [
    "I love pizza", 
    "Pizza is the best", 
    "I love pasta", 
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range=(1,3)) 

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out()) 
print("\n BoW Matrix: \n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'is great' 'is the' 'is the best' 'love' 'love pasta'
 'love pizza' 'pasta' 'pasta is' 'pasta is great' 'pizza' 'pizza is'
 'pizza is the' 'the' 'the best']

 BoW Matrix:
 [[0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0]]

## TF-IDF

In [92]:
from sklearn.feature_extraction.text import TfidfVectorizer 

documents = [
    "I love pizza", 
    "Pizza is the best", 
    "I love pasta", 
    "Pasta is great"
]

vectorizer = TfidfVectorizer() 

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out()) 
print("\n TF-IDF Matrix: \n", X.toarray())

Vocabulary: ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

 TF-IDF Matrix:
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]

## Model Building

In [113]:
X = df["title"]
y = df['emotions']

In [114]:
X.head()

0                                didnt feel humiliated
1    go feeling hopeless damned hopeful around some...
2            im grabbing minute post feel greedy wrong
3    ever feeling nostalgic fireplace know still pr...
4                                      feeling grouchy
Name: title, dtype: object

In [115]:
from sklearn.model_selection import train_test_split

In [116]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [117]:
X_train

8917     feeling quite pleased fact one coupon use grocery
9453               stressed finally come end feel relieved
2829     feel blessed know immense family supporters co...
9681                       didnt feel like missed anything
12246            feel listless unable imagine ever working
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: title, Length: 10720, dtype: object

In [118]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [119]:
bow_vect = CountVectorizer()

In [120]:
X_train_bow = bow_vect.fit_transform(X_train)

In [121]:
X_train_bow

<10720x12147 sparse matrix of type '<class 'numpy.int64'>'
	with 96942 stored elements in Compressed Sparse Row format>

In [123]:
X_test_bow = bow_vect.transform(X_test)

In [124]:
from sklearn.naive_bayes import MultinomialNB 
from sklearn.metrics import accuracy_score

In [125]:
nb_model = MultinomialNB()

In [127]:
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [128]:
y_pred_nb = nb_model.predict(X_test_bow)

In [129]:
accuracy_score(y_test, y_pred_nb)

0.7647727272727273

In [131]:
tdidf_model = TfidfVectorizer() 

X_train_tfidf = tdidf_model.fit_transform(X_train)
X_test_tfidf = tdidf_model.transform(X_test)

In [132]:
nb_model2 = MultinomialNB() 
nb_model2.fit(X_train_tfidf, y_train)

MultinomialNB()

In [133]:
tfidf_pred = nb_model2.predict(X_test_tfidf)

accuracy_score(y_test, tfidf_pred)

0.6606060606060606

## Logistic Regression with TF-IDF

In [138]:
from sklearn.linear_model import LogisticRegression 

lr_model = LogisticRegression(max_iter=1000) 

lr_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [139]:
y_lr_pred = lr_model.predict(X_test_tfidf)

accuracy_score(y_test, y_lr_pred)

0.8479166666666667