In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [3]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [4]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [5]:
X = df.drop('needs_water',axis=1)
y = df['needs_water']

### Note: For ML models we used StandardScaler to scale down the values but here in DL we use Normalization to scale down the values between 0 to 1.

In [6]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [7]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

In [9]:
#------------------------------------
# Activation Function
#--------------------------------------

model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)), #Input Layer
    layers.Dense(8,activation='relu'),   #Hidden Layer and here 8 neurons we can add any number of neurons in form of 2^x form
    layers.Dense(4,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [11]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics=['accuracy'])

In [13]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values, y_test.values),
    epochs = 100, batch_size = 4, verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8125 - loss: 0.5732 - val_accuracy: 0.2500 - val_loss: 0.6771
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.6030 - val_accuracy: 0.2500 - val_loss: 0.6742
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8125 - loss: 0.5747 - val_accuracy: 0.2500 - val_loss: 0.6712
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7188 - loss: 0.6017 - val_accuracy: 0.2500 - val_loss: 0.6684
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.6083 - val_accuracy: 0.2500 - val_loss: 0.6656
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7188 - loss: 0.5782 - val_accuracy: 0.2500 - val_loss: 0.6632
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5843 - val_accuracy: 0.2500 - val_loss: 0.6614
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5914 - val_accuracy: 0.2500 - val_loss: 0.6595
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8438 - loss: 0.5645 - val_accuracy: 0.2500 - val_loss: 0.6576
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6562 - loss: 0.6054 - val_accuracy: 0.2500 - val_loss: 0.6562
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5807 - val_accuracy: 0.2500 - val_loss: 0.6558
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7188 - loss: 0.5964 - val_accuracy: 0.2500 - val_loss: 0.6543
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7812 - loss: 0.5641 - val_accuracy: 0.2500 - val_loss: 0.6536
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7812 - loss: 0.5827 - val_accuracy: 0.2500 - val_loss: 0.6522
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8125 - loss: 0.5719 - val_accuracy: 0.2500 - val_loss: 0.6511
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8125 - loss: 0.5583 - val_accuracy: 0.5000 - val_loss: 0.6506
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7500 - loss: 0.5736 - val_accuracy: 0.5000 - val_loss: 0.6499
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7188 - loss: 0.5801 - val_accuracy: 0.5000 - val_loss: 0.6489
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8125 - loss: 0.5537 - val_accuracy: 0.5000 - val_loss: 0.6484
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.7500 - loss: 0.5718 - val_accuracy: 0.7500 - val_loss: 0.6473
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8125 - loss: 0.5678 - val_accuracy: 0.7500 - val_loss: 0.6459
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7917 - loss: 0.5842 - val_accuracy: 0.7500 - val_loss: 0.6457
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.6562 - loss: 0.5940 - val_accuracy: 0.7500 - val_loss: 0.6453
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7500 - loss: 0.5579 - val_accuracy: 0.7500 - val_loss: 0.6442
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7188 - loss: 0.5680 - val_accuracy: 0.7500 - val_loss: 0.6438
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.8438 - loss: 0.5478 - val_accuracy: 0.7500 - val_loss: 0.6425
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8229 - loss: 0.5764 - val_accuracy: 0.7500 - val_loss: 0.6414
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8438 - loss: 0.5197 - val_accuracy: 0.7500 - val_loss: 0.6399
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8229 - loss: 0.5855 - val_accuracy: 0.7500 - val_loss: 0.6395
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9167 - loss: 0.5404 - val_accuracy: 0.7500 - val_loss: 0.6383
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8229 - loss: 0.5725 - val_accuracy: 0.7500 - val_loss: 0.6373
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8125 - loss: 0.5334 - val_accuracy: 0.7500 - val_loss: 0.6363
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.7812 - loss: 0.5608 - val_accuracy: 0.7500 - val_loss: 0.6351
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8438 - loss: 0.5353 - val_accuracy: 0.7500 - val_loss: 0.6339
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8854 - loss: 0.5340 - val_accuracy: 0.7500 - val_loss: 0.6329
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8125 - loss: 0.5161 - val_accuracy: 0.7500 - val_loss: 0.6321
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8854 - loss: 0.5492 - val_accuracy: 0.7500 - val_loss: 0.6314
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8542 - loss: 0.5430 - val_accuracy: 0.7500 - val_loss: 0.6305
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7292 - loss: 0.5444 - val_accuracy: 0.7500 - val_loss: 0.6297
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.5137 - val_accuracy: 0.7500 - val_loss: 0.6288
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8854 - loss: 0.5353 - val_accuracy: 0.7500 - val_loss: 0.6286
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8854 - loss: 0.5271 - val_accuracy: 0.7500 - val_loss: 0.6278
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8229 - loss: 0.5608 - val_accuracy: 0.7500 - val_loss: 0.6269
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8854 - loss: 0.5474 - val_accuracy: 0.7500 - val_loss: 0.6268
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8854 - loss: 0.5308 - val_accuracy: 0.7500 - val_loss: 0.6261
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8229 - loss: 0.5561 - val_accuracy: 0.7500 - val_loss: 0.6252
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8854 - loss: 0.5106 - val_accuracy: 0.7500 - val_loss: 0.6242
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8854 - loss: 0.5108 - val_accuracy: 0.7500 - val_loss: 0.6229
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9167 - loss: 0.4992 - val_accuracy: 0.7500 - val_loss: 0.6221
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.5326 - val_accuracy: 0.7500 - val_loss: 0.6212
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5325 - val_accuracy: 0.7500 - val_loss: 0.6211
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.5355 - val_accuracy: 0.7500 - val_loss: 0.6203
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.5503 - val_accuracy: 0.7500 - val_loss: 0.6202
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9271 - loss: 0.5297 - val_accuracy: 0.7500 - val_loss: 0.6189
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.5306 - val_accuracy: 0.7500 - val_loss: 0.6181
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5406 - val_accuracy: 0.7500 - val_loss: 0.6180
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8646 - loss: 0.5420 - val_accuracy: 0.7500 - val_loss: 0.6174
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.5166 - val_accuracy: 0.7500 - val_loss: 0.6167
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9271 - loss: 0.5150 - val_accuracy: 0.7500 - val_loss: 0.6161
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8646 - loss: 0.5665 - val_accuracy: 0.7500 - val_loss: 0.6156
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9583 - loss: 0.5131 - val_accuracy: 0.7500 - val_loss: 0.6145
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9583 - loss: 0.5240 - val_accuracy: 0.7500 - val_loss: 0.6139
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.4894 - val_accuracy: 0.7500 - val_loss: 0.6130
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8646 - loss: 0.5389 - val_accuracy: 0.7500 - val_loss: 0.6125
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8646 - loss: 0.4960 - val_accuracy: 0.7500 - val_loss: 0.6119
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9583 - loss: 0.5128 - val_accuracy: 0.7500 - val_loss: 0.6111
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.9583 - loss: 0.5094 - val_accuracy: 0.7500 - val_loss: 0.6101
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5257 - val_accuracy: 0.7500 - val_loss: 0.6095
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5505 - val_accuracy: 0.7500 - val_loss: 0.6088
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.4699 - val_accuracy: 0.7500 - val_loss: 0.6082
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.4990 - val_accuracy: 0.7500 - val_loss: 0.6070
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.5585 - val_accuracy: 0.7500 - val_loss: 0.6063
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.5351 - val_accuracy: 0.7500 - val_loss: 0.6057
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.5295 - val_accuracy: 0.7500 - val_loss: 0.6051
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.5261 - val_accuracy: 0.7500 - val_loss: 0.6041
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8646 - loss: 0.5423 - val_accuracy: 0.7500 - val_loss: 0.6027
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9583 - loss: 0.4690 - val_accuracy: 0.7500 - val_loss: 0.6018
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8646 - loss: 0.5183 - val_accuracy: 0.7500 - val_loss: 0.6010
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9583 - loss: 0.5102 - val_accuracy: 0.7500 - val_loss: 0.6000
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8646 - loss: 0.5267 - val_accuracy: 0.7500 - val_loss: 0.5993
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4781 - val_accuracy: 0.7500 - val_loss: 0.5987
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.5042 - val_accuracy: 0.7500 - val_loss: 0.5983
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.5001 - val_accuracy: 0.7500 - val_loss: 0.5976
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.9271 - loss: 0.4989 - val_accuracy: 0.7500 - val_loss: 0.5958
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.8646 - loss: 0.4988 - val_accuracy: 0.7500 - val_loss: 0.5966
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9583 - loss: 0.4712 - val_accuracy: 0.7500 - val_loss: 0.5948
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9271 - loss: 0.4728 - val_accuracy: 0.7500 - val_loss: 0.5932
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5298 - val_accuracy: 0.7500 - val_loss: 0.5922
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.9271 - loss: 0.5092 - val_accuracy: 0.7500 - val_loss: 0.5918
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.5246 - val_accuracy: 0.7500 - val_loss: 0.5916
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4711 - val_accuracy: 0.7500 - val_loss: 0.5924
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.8646 - loss: 0.5072 - val_accuracy: 0.7500 - val_loss: 0.5914
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5231 - val_accuracy: 0.7500 - val_loss: 0.5908
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.4744 - val_accuracy: 0.7500 - val_loss: 0.5895
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.8646 - loss: 0.4889 - val_accuracy: 0.7500 - val_loss: 0.5891
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4864 - val_accuracy: 0.7500 - val_loss: 0.5876
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.4908 - val_accuracy: 0.7500 - val_loss: 0.5854
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9583 - loss: 0.4478 - val_accuracy: 0.7500 - val_loss: 0.5837
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 1.0000 - loss: 0.4734 - val_accuracy: 0.7500 - val_loss: 0.5833
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 1.0000 - loss: 0.5086 - val_accuracy: 0.7500 - val_loss: 0.5829

1. **loss**
- This is the training loss.
- It tells you how wrong your model’s predictions are on the training set, according to the loss function you chose (in your case: binary
cross-entropy).
- Lower is better.
- During training, the model tries to reduce this number by updating weights with gradient descent.

2. **accuracy**
- This is the training accuracy.
- It tells you what fraction of training samples the model is correctly predicting.
- Example: If you have 100 samples and the model gets 80 correct → accuracy = 0.80 (80%).

3. **val_loss**
- This is the validation loss.
- After generalizing well or just memorizingion set (the split you gave with validation_data=...) and calculates the loss on that unseen data.
- This tells you whether your model is generalizing well or just memorizing the training data.

4. **val_accuracy**
- This is the validation accuracy.
- It’s the percentage of correct predictions on the validation set.
- If accuracy is high but val_accuracy is low → your model is probably overfitting (memorizing training but failing on new data).

**Where to pay attention**
- loss & accuracy = how well model is doing on training data.
- val_loss & val_accuracy = how well model is doing on new unseen data.
- Always pay more attention to validation metrics because that shows how the model will behave in the real world.